//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Emails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Emails", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт на сайті ffi-eco.com було активовано.
        /// </summary>
        internal static string AccountActivated {
            get {
                return ResourceManager.GetString("AccountActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт було активовано.
        /// </summary>
        internal static string AccountActivatedHeader {
            get {
                return ResourceManager.GetString("AccountActivatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;meta content=\&quot;text/html;charset=utf-8\&quot; /&gt;&lt;/head&gt;&lt;body&gt;&lt;p&gt;Шановний {0} , &lt;/p&gt;&lt;p&gt; Щоб підтвердити ваш аккаунт, будь ласка, клікніть на наступне посилання:&lt;/p&gt;&lt;p&gt;&lt;a href=&apos;{1}&apos; target=\&quot;_blank\&quot;&gt;{1}&lt;/a&gt;&lt;/p&gt;&lt;div&gt;З повагою,&lt;/div&gt;&lt;div&gt;FFI-ECO&lt;/div&gt;&lt;p&gt;Не відповідайте на це повідомлення, активізаційний лінк є приватним.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;
        ///
        ///&lt;html&gt;&lt;head&gt;&lt;meta content=\&quot;text/html;charset=utf-8\&quot; /&gt;&lt;/head&gt;&lt;body&gt;&lt;p&gt;Уважаемый {0} , &lt;/p&gt;&lt;p&gt; Чтобы подтвердить ваш аккаунт, пожалуйста, кликните на следущую ссы [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountConfirmationText {
            get {
                return ResourceManager.GetString("AccountConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шановний {0}, термін дії вашого аккаунта в системі FFI-ECO було продовжено на {1} місяців, до {2} &lt;br/&gt;&lt;br/&gt;
        ///Дорогой {0}, срок действия вашего аккаунта в системе FFI-ECO продолжен на {1} месяцев, до {2}.
        /// </summary>
        internal static string AccountEpirationExtended {
            get {
                return ResourceManager.GetString("AccountEpirationExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пользователь: {0}.
        /// </summary>
        internal static string NewUserBody {
            get {
                return ResourceManager.GetString("NewUserBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ с сайта FFI-ECO.COM.
        /// </summary>
        internal static string OrderCreatedClientSubject {
            get {
                return ResourceManager.GetString("OrderCreatedClientSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш заказ принят, в ближайшее время с вами свяжется менеджер для уточнения деталей доставки..
        /// </summary>
        internal static string OrderCreatedClientText {
            get {
                return ResourceManager.GetString("OrderCreatedClientText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0} &lt;br/&gt; Email: {1} &lt;br/&gt; Phone: {2} &lt;br/&gt; Adress: {3} &lt;br/&gt;Products: &lt;br/&gt; {4} &lt;br/&gt; Total: {5} uah.
        /// </summary>
        internal static string OrderCreatedText {
            get {
                return ResourceManager.GetString("OrderCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Client is willing to contact a owner of this car &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;&lt;br/&gt;
        ///Client contact information: {1}&lt;br/&gt;&lt;br/&gt;
        ///Клиент вашего сайта хотел бы связаться с владельцем этого автомобиля &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;&lt;br/&gt;
        ///Контактная информация клиента: {1}&lt;br/&gt;&lt;br/&gt;
        ///Клієнт вашего сайта бажає звязатися з власником цього авто &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;&lt;br/&gt;
        ///Контактна інформація клієнта: {1}&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///.
        /// </summary>
        internal static string ResultContactOwner {
            get {
                return ResourceManager.GetString("ResultContactOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired email name: {0} &lt;br/&gt;
        ///Reply to: {1}.
        /// </summary>
        internal static string UniqEmailRequest {
            get {
                return ResourceManager.GetString("UniqEmailRequest", resourceCulture);
            }
        }
    }
}
