//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт вже активовано, будь ласка, завітайте до сторінки Партнерька панель.
        /// </summary>
        internal static string AccountAlreadyVerified {
            get {
                return ResourceManager.GetString("AccountAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт було створено, але ще не активовано. Після того, як адміністрація перевірить чи зареєструвались ви як дистриб&apos;ютор компанії FFI (чи дійсно ви є наш партнер), ви отримаєте email повідомлення про активацію вашого аккаунта..
        /// </summary>
        internal static string AccountBeingChecked {
            get {
                return ResourceManager.GetString("AccountBeingChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити пароль.
        /// </summary>
        internal static string AccountChangePassword {
            get {
                return ResourceManager.GetString("AccountChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вітаємо! Ваш аккаунт набув статус партнерського, термін дії ви можете перевірити та змінити у Партнерській Панелі..
        /// </summary>
        internal static string AccountPartnershipCreated {
            get {
                return ResourceManager.GetString("AccountPartnershipCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дякуємо за реєстрацію! Для того, щоб ваш аккаунт набув статусу партнерського, будь ласка, заповніть всі поля та продовжіть термін дії аккаунта.
        /// </summary>
        internal static string AccountRegistered {
            get {
                return ResourceManager.GetString("AccountRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваші данні було оновлено.
        /// </summary>
        internal static string AccountUpdated {
            get {
                return ResourceManager.GetString("AccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний код активації аккаунта.
        /// </summary>
        internal static string AccountWrongConfirmation {
            get {
                return ResourceManager.GetString("AccountWrongConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стати партнером.
        /// </summary>
        internal static string BecomePartner {
            get {
                return ResourceManager.GetString("BecomePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        internal static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надіслати.
        /// </summary>
        internal static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почати бізнес в FFI з партнерською програмою FFI-ECO.
        /// </summary>
        internal static string BusinessHint {
            get {
                return ResourceManager.GetString("BusinessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш кошик замовлень.
        /// </summary>
        internal static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати до кошику.
        /// </summary>
        internal static string CartAdd {
            get {
                return ResourceManager.GetString("CartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продовжити покупки.
        /// </summary>
        internal static string CartContinueShopping {
            get {
                return ResourceManager.GetString("CartContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оформити замовлення.
        /// </summary>
        internal static string CartCreateOrder {
            get {
                return ResourceManager.GetString("CartCreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш кошик пустий.
        /// </summary>
        internal static string CartEmpty {
            get {
                return ResourceManager.GetString("CartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готівка.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страховка від будь-яких можливих пошкоджень двигуна через продукцію компанії FFI.
        /// </summary>
        internal static string CertificateInsurance {
            get {
                return ResourceManager.GetString("CertificateInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Висновок державної санітарно-епідеміологічної експертизи про безпеку продуктів FFI.
        /// </summary>
        internal static string CertificateMOZ {
            get {
                return ResourceManager.GetString("CertificateMOZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Застраховано AUTO OWNERS INSURANCE COMPANY на суму 1 000 000$ на кожен страховий
        ///    випадок.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Має дозвіл EPA - Environmental Protection Agency (американьского суспільства захисту
        ///    навколишнього середовища) № 218820001. Перевірена на безпеку американським міністерством
        ///    труда - MSDS - № CRF 1910.120029. Технологія запатентована і продукцію можна купити
        ///    у дистриб&apos;юторів компанії FFI.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string CertificateText {
            get {
                return ResourceManager.GetString("CertificateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сертифікати якості та гарантії.
        /// </summary>
        internal static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Львів.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторіть пароль.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дякуємо за ваше повідомлення! Найближчим часом на зазначену вами Email адресу прийде відповідь..
        /// </summary>
        internal static string ContactEmailSent {
            get {
                return ResourceManager.GetString("ContactEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактна інформація.
        /// </summary>
        internal static string ContactsInfo {
            get {
                return ResourceManager.GetString("ContactsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кредитна картка.
        /// </summary>
        internal static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грн.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email адреса.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приклад.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я забув свій пароль :(.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З чого почати.
        /// </summary>
        internal static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Як правильно почати бізнес з FFI та партерською програмою FFI-ECO.
        /// </summary>
        internal static string GettingStartedBusiness {
            get {
                return ResourceManager.GetString("GettingStartedBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крок 1. Реєстрація та оплата акаунта дистриб&apos;ютора (Starter kit 30 $) на головному сайті FFI. .
        /// </summary>
        internal static string GettingStartedBusinessStep1 {
            get {
                return ResourceManager.GetString("GettingStartedBusinessStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;
        ///                        Крок 2. Реєстрація партнерської програми FFI-ECO
        ///        &lt;/h3&gt;
        ///        &lt;p&gt;
        ///            Бонуси від реєстрації в нашій партнерській програмі:
        ///            &lt;ul&gt;
        ///                
        ///                &lt;li&gt;- Персональний сайт з ЯКІСНИМ і УНІКАЛЬНИМ контентом: ознайомче відео,
        ///                    технічні деталі роботи продукту, реальні практичні результати &lt;/li&gt; 
        /// &lt;li&gt;- Персональний інтернет магазин з усім спектром продукції компанії&lt;/li&gt;
        /// &lt;li&gt;- Персональна Email адреса з унікальн [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GettingStartedBusinessStep2 {
            get {
                return ResourceManager.GetString("GettingStartedBusinessStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;
        ///            Крок 3. Вивчити Маркетинг, Інструменти для роботи, Особливості Партнерської програми
        ///        &lt;/h3&gt;
        ///        &lt;p&gt;
        ///            Ці знання дадуть вам можливість ШВИДКО, ПРАВИЛЬНО і максимально ЕФЕКТИВНО почати
        ///            свій бізнес і заробіток в компанії Forever Freedom International.
        ///        &lt;/p&gt;
        ///        &lt;span class=&quot;field-validation-error&quot;&gt;Доступно після реєстрації партнерської програми
        ///            FFI-ECO &lt;/span&gt;.
        /// </summary>
        internal static string GettingStartedBusinessStep3 {
            get {
                return ResourceManager.GetString("GettingStartedBusinessStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;
        ///                &lt;font color=&apos;red&apos;&gt;ПРАВИЛЬНО&lt;/font&gt;
        ///                &lt;br /&gt;
        ///                 почати свій бізнес і працювати&lt;br /&gt;
        ///                ЭФЕКТИВНО
        ///            &lt;/h2&gt;.
        /// </summary>
        internal static string GettingStartedBusinessSub {
            get {
                return ResourceManager.GetString("GettingStartedBusinessSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;
        ///&lt;font color=&quot;red&quot;&gt;ПРАВИЛЬНО&lt;/font&gt;
        ///&lt;br&gt;
        ///почати користуватися продукцією та отримати ЕКОНОМІЮ
        ///&lt;/h2&gt;.
        /// </summary>
        internal static string GettingStartedProduction {
            get {
                return ResourceManager.GetString("GettingStartedProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Придбати продукцію ви також можете на нашому сайті, дивіться розділ .
        /// </summary>
        internal static string GettingStartedProductionBuy {
            get {
                return ResourceManager.GetString("GettingStartedProductionBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-яку консультацію по використанню продукції Компанії FFI, ви можете отримати в
        ///            зручному для вас форматі, дивіться розділ.
        /// </summary>
        internal static string GettingStartedProductionConsulting {
            get {
                return ResourceManager.GetString("GettingStartedProductionConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ol id=&quot;instruction&quot;&gt;
        ///    &lt;li&gt;
        ///        &lt;h3&gt;
        ///            1. Визначення реальної витрати палива&lt;/h3&gt;
        ///        &lt;p&gt;
        ///             Виберіть АЗС на виїзді зі свого міста (бажано АЗС, на якому ви найчастіше
        ///            заправляєтеся). Заправте паливо до горловини бака, щоб його було видно в горловині
        ///            (Не до відстрілу заправного пістолета, а до горловини бака, це важливо). Скиньте
        ///            лічильник добового пробігу авто на 0 і починайте рух з &quot;крейсерською швидкістю&quot;
        ///            80-90 км/год, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GettingStartedProductionText {
            get {
                return ResourceManager.GetString("GettingStartedProductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гість.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На головну сторінку.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Як працює продукція.
        /// </summary>
        internal static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;height: 100%;&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td valign=&quot;top&quot;&gt;
        ///                &lt;br&gt;
        ///                &lt;table class=&quot;contentpaneopen&quot;&gt;
        ///                    &lt;tbody&gt;
        ///                        &lt;tr&gt;
        ///                            &lt;td valign=&quot;top&quot;&gt;
        ///                                &lt;p style=&quot;text-align: justify;&quot;&gt;
        ///                                    &lt;strong&gt;Розглянемо 3 фактора, завдяки яким і відбувається економія палива:&lt;/strong&gt;&lt;/p&gt;
        ///                                &lt;p style=&quot;text-align: j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HowItWorksText {
            get {
                return ResourceManager.GetString("HowItWorksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зображення.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to введено невірно.
        /// </summary>
        internal static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інструкція.
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При реєстрації в компанії Forever Freedom International Ви самостійно вибираєте свій логін, що складається з латинських букв і цифр, а за тим оплачуєте стартовий пакет &quot;Starter Kit&quot; (30$).&lt;br/&gt; Звертаємо увагу, що Ваша платіжна карта, яку Ви використовуватимете для оплати, має бути обов&apos;язково придатна для оплати через інтернет, оскільки оплата здійснюється на рахунок американської компанії. Тобто Вам необхідно замовити в свого оператора банку карту Visa Інтернет або іншу подібну, за тим переказати на неї н [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstructionText {
            get {
                return ResourceManager.GetString("InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страховой полис.
        /// </summary>
        internal static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        internal static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to І&apos;мя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукція.
        /// </summary>
        internal static string NavProduction {
            get {
                return ResourceManager.GetString("NavProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити аккаунт.
        /// </summary>
        internal static string NewAccountTitle {
            get {
                return ResourceManager.GetString("NewAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація замовника.
        /// </summary>
        internal static string OrderContactInfo {
            get {
                return ResourceManager.GetString("OrderContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше замовлення прийнято, найближчим часом з вами зв&apos;яжеться менеджер для уточнення деталей замовлення..
        /// </summary>
        internal static string OrderCreated {
            get {
                return ResourceManager.GetString("OrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо ви мешкаєте на території держави {0}, то товар вам буде надіслано накладеним платежем за допомогою служби доставки &quot;{1}&quot;. Якщо ви проживаєте на території іншої держави, товар вам слідує придбати у &lt;a href=&quot;http://{2}.myffi.biz/&quot; class=&quot;blue&quot;  target=&quot;_blank&quot;&gt;зовнішньому магазині FFI&lt;/a&gt;, і він вам буде доставлений кур&apos;єром до дому..
        /// </summary>
        internal static string OrderShippingCondition {
            get {
                return ResourceManager.GetString("OrderShippingCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса.
        /// </summary>
        internal static string PartnerAddress {
            get {
                return ResourceManager.GetString("PartnerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити запит на скриньку.
        /// </summary>
        internal static string PartnerBtnCreateEmail {
            get {
                return ResourceManager.GetString("PartnerBtnCreateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        internal static string PartnerCity {
            get {
                return ResourceManager.GetString("PartnerCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email для повідомлень та замовлень.
        /// </summary>
        internal static string PartnerContactsEmail {
            get {
                return ResourceManager.GetString("PartnerContactsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Країна.
        /// </summary>
        internal static string PartnerCountry {
            get {
                return ResourceManager.GetString("PartnerCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація партнера.
        /// </summary>
        internal static string PartnerCreateHeading {
            get {
                return ResourceManager.GetString("PartnerCreateHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ці дані будуть використовуватись у розділі Контакти на вашому сайті, заповніть їх корректно, щоб клієнти мали змогу зв&apos;язатись з Вами.
        /// </summary>
        internal static string PartnerCreateHint {
            get {
                return ResourceManager.GetString("PartnerCreateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служба доставки для відправки товару.
        /// </summary>
        internal static string PartnerDeliveryService {
            get {
                return ResourceManager.GetString("PartnerDeliveryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви вже маєте партнерський аккаунт.
        /// </summary>
        internal static string PartnerExist {
            get {
                return ResourceManager.GetString("PartnerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт дійсній до.
        /// </summary>
        internal static string PartnerExpirationDate {
            get {
                return ResourceManager.GetString("PartnerExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продовжити термін дії.
        /// </summary>
        internal static string PartnerExtend {
            get {
                return ResourceManager.GetString("PartnerExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої дані.
        /// </summary>
        internal static string PartnerInfo {
            get {
                return ResourceManager.GetString("PartnerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to місяців.
        /// </summary>
        internal static string PartnerMonths {
            get {
                return ResourceManager.GetString("PartnerMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to І&apos;мя та Прізвище.
        /// </summary>
        internal static string PartnerName {
            get {
                return ResourceManager.GetString("PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не дійсний.
        /// </summary>
        internal static string PartnerNotActive {
            get {
                return ResourceManager.GetString("PartnerNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка, введіть свої дані для користування партнерською програмою.
        /// </summary>
        internal static string PartnerNotExist {
            get {
                return ResourceManager.GetString("PartnerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнерська панель.
        /// </summary>
        internal static string PartnerPanel {
            get {
                return ResourceManager.GetString("PartnerPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для оплати рахунку кредитною карткою необхідна реєстрація в системі EasyPay.
        /// </summary>
        internal static string PartnerPaymentCardHint {
            get {
                return ResourceManager.GetString("PartnerPaymentCardHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата терміну дії аккаунта користувача {0}.
        /// </summary>
        internal static string PartnerPaymentDescription {
            get {
                return ResourceManager.GetString("PartnerPaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть термін продовження дії аккаунта.
        /// </summary>
        internal static string PartnerPaymentSelectHint {
            get {
                return ResourceManager.GetString("PartnerPaymentSelectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума до сплати.
        /// </summary>
        internal static string PartnerPaymentSumDescr {
            get {
                return ResourceManager.GetString("PartnerPaymentSumDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string PartnerPhone {
            get {
                return ResourceManager.GetString("PartnerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реферал.
        /// </summary>
        internal static string PartnerReferal {
            get {
                return ResourceManager.GetString("PartnerReferal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса вашого сайту &lt;a href=&apos;http://{0}.ffi-eco.com&apos; class=&apos;blue&apos;&gt;{0}.ffi-eco.com&lt;/a&gt;.
        /// </summary>
        internal static string PartnerReferalText {
            get {
                return ResourceManager.GetString("PartnerReferalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корисні ресурси.
        /// </summary>
        internal static string PartnerResources {
            get {
                return ResourceManager.GetString("PartnerResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви можете отримати унікальну поштову скриньку з адресою &lt;span class=&apos;blue&apos;&gt; [ім&apos;я]@ffi-eco.com&lt;/span&gt;, для цього введіть бажане імя та натисніть кнопку &quot;Створити запит на скриньку&quot;. Всі деталі вашої нової поштової скриньки будуть надіслані вам на Email, з яким ви зареєструвались у системі, як тільки ії буде створено..
        /// </summary>
        internal static string PartnerUniqEmail {
            get {
                return ResourceManager.GetString("PartnerUniqEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви можете змінити відео &quot;Презентація&quot; на своєму сайті. Для цього вставте у це поле html код, який вам надає Youtube &lt;br/&gt;
        ///        &lt;img src=&quot;../../Content/images/youtube.png&quot; height=&apos;400&apos; width=&apos;500&apos;/&gt;&lt;br/&gt;
        ///        Ваше відео має містити: &lt;br/&gt;
        ///        - достовірну інформацію про компанію FFI та ії продукцію&lt;br/&gt;
        ///        - приємний задній план (не має бути старих килимів та інших речей, що погано виглядають)&lt;br/&gt;
        ///        - охайний вигляд спікера&lt;br/&gt;
        ///        - добре поставлену вимову &lt;br/&gt;
        ///- триваліст [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PartnerYouTubeHint {
            get {
                return ResourceManager.GetString("PartnerYouTubeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувача з таким логіном не знайдено.
        /// </summary>
        internal static string PasswordRecoveryFail {
            get {
                return ResourceManager.GetString("PasswordRecoveryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш новий пароль було вислано на вашу поштову скриньку, з якою ви реєструвалися в системі.
        /// </summary>
        internal static string PasswordRecoverySuccess {
            get {
                return ResourceManager.GetString("PasswordRecoverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата рахунку НЕ ВІДБУЛАСЬ, будь ласка, звяжіться з адміністрацією сайта у розділі Контакти.
        /// </summary>
        internal static string PaymentFailure {
            get {
                return ResourceManager.GetString("PaymentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стан оплати рахунку.
        /// </summary>
        internal static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата рахунку відбулась успішно. Дякуємо за користування нашим сервісом!.
        /// </summary>
        internal static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практичні результати.
        /// </summary>
        internal static string PracticalResults {
            get {
                return ResourceManager.GetString("PracticalResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукція.
        /// </summary>
        internal static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Важливо!!! &lt;br/&gt;&lt;br/&gt;Будь ласка, при реєстрації використовуйте той самий логін, з яким ви зареєструвались у системі FFI, щоб ми змогли перевірити чи дійсна ваша реєстрація та чи є ви нашим партнером. Якщо ви ще не зареєструвались як дистриб&apos;ютор компанії FFI, будь ласка, відвідайте цю сторінку {0} &lt;br/&gt;&lt;br/&gt;Також, будь ласка, корректно заповніть поле Email адреси, бо без діючої електронної поштової скриньки ви не зможете активувати аккаунт. Якщо після реєстрації протягом 24 годин ви не отримали реєстраційну [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistrationHint {
            get {
                return ResourceManager.GetString("RegistrationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш запит було створено.
        /// </summary>
        internal static string RequestCreated {
            get {
                return ResourceManager.GetString("RequestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш результат одобрено.
        /// </summary>
        internal static string ResultActivated {
            get {
                return ResourceManager.GetString("ResultActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звя&apos;затись з власником цього автомобіля.
        /// </summary>
        internal static string ResultConnectOwner {
            get {
                return ResourceManager.GetString("ResultConnectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть свій телефон або Email адресу.
        /// </summary>
        internal static string ResultContactOwnerHint {
            get {
                return ResourceManager.GetString("ResultContactOwnerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш результат проходить верифікацію.
        /// </summary>
        internal static string ResultIsReviewed {
            get {
                return ResourceManager.GetString("ResultIsReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виробник.
        /// </summary>
        internal static string ResultsSelectManufacturer {
            get {
                return ResourceManager.GetString("ResultsSelectManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        internal static string ResultsSelectModel {
            get {
                return ResourceManager.GetString("ResultsSelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свої ресурси.
        /// </summary>
        internal static string SelfResources {
            get {
                return ResourceManager.GetString("SelfResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свій результат використання продукції (відео з Youtube).
        /// </summary>
        internal static string SelfResult {
            get {
                return ResourceManager.GetString("SelfResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надіслати повідомлення.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, заповніть всі поля форми.
        /// </summary>
        internal static string SendMessageFail {
            get {
                return ResourceManager.GetString("SendMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презентація.
        /// </summary>
        internal static string TestDrive {
            get {
                return ResourceManager.GetString("TestDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;
        ///    Про компанію FFI&lt;/h3&gt;
        ///&lt;p&gt;
        ///    Як часто відбувається, що ми втрачаємо своє здоров&apos;я, заробляючи гроші, а потім
        ///    витрачаємо гроші, відновлюючи втрачене здоров&apos;я. Якийсь замкнутий круг виходить...
        ///    &lt;br /&gt;
        ///    Але не варто зневірюватись!
        ///    &lt;br /&gt;
        ///    Ми познайомимо Вас з компанією, в якої є рішення, завдяки яким, Ви можемо змінити
        ///    ситуацію на краще. Це - &quot;FOREVER FREEDOM INTERNATIONAL&quot; - компанія, яка піклується
        ///    про довкілля, наше здоров&apos;я, надаючи бажаючим виняткову можливіст [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDriveText {
            get {
                return ResourceManager.GetString("TestDriveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFI Ecology.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разом.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Україна.
        /// </summary>
        internal static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
