//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Web.Mvc;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ffiModel", "FK_Products_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Internet.Models.Category), "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Internet.Models.Product), true)]
[assembly: EdmRelationshipAttribute("ffiModel", "FK_Banners_Partners", "Partner", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Internet.Models.Partner), "Banner", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Internet.Models.Banner), true)]
[assembly: EdmRelationshipAttribute("ffiModel", "FK_Payments_Partners", "Partner", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Internet.Models.Partner), "Payment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Internet.Models.Payment), true)]
[assembly: EdmRelationshipAttribute("ffiModel", "FK_Results_Partners", "Partner", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Internet.Models.Partner), "Result", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Internet.Models.Result), true)]

#endregion

namespace Internet.Models
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ffiEntities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new ffiEntities object using the connection string found in the 'ffiEntities' section of the application configuration file.
        /// </summary>
        public ffiEntities()
            : base("name=ffiEntities", "ffiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new ffiEntities object.
        /// </summary>
        public ffiEntities(string connectionString)
            : base(connectionString, "ffiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new ffiEntities object.
        /// </summary>
        public ffiEntities(EntityConnection connection)
            : base(connection, "ffiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Payment> Payments
        {
            get
            {
                if ((_Payments == null))
                {
                    _Payments = base.CreateObjectSet<Payment>("Payments");
                }
                return _Payments;
            }
        }
        private ObjectSet<Payment> _Payments;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Slide> Slides
        {
            get
            {
                if ((_Slides == null))
                {
                    _Slides = base.CreateObjectSet<Slide>("Slides");
                }
                return _Slides;
            }
        }
        private ObjectSet<Slide> _Slides;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FAQ> FAQs
        {
            get
            {
                if ((_FAQs == null))
                {
                    _FAQs = base.CreateObjectSet<FAQ>("FAQs");
                }
                return _FAQs;
            }
        }
        private ObjectSet<FAQ> _FAQs;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Result> Results
        {
            get
            {
                if ((_Results == null))
                {
                    _Results = base.CreateObjectSet<Result>("Results");
                }
                return _Results;
            }
        }
        private ObjectSet<Result> _Results;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Banner> Banners
        {
            get
            {
                if ((_Banners == null))
                {
                    _Banners = base.CreateObjectSet<Banner>("Banners");
                }
                return _Banners;
            }
        }
        private ObjectSet<Banner> _Banners;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Partner> Partners
        {
            get
            {
                if ((_Partners == null))
                {
                    _Partners = base.CreateObjectSet<Partner>("Partners");
                }
                return _Partners;
            }
        }
        private ObjectSet<Partner> _Partners;

        #endregion

        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Payments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPayments(Payment payment)
        {
            base.AddObject("Payments", payment);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Slides EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSlides(Slide slide)
        {
            base.AddObject("Slides", slide);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the FAQs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFAQs(FAQ fAQ)
        {
            base.AddObject("FAQs", fAQ);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Results EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResults(Result result)
        {
            base.AddObject("Results", result);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Banners EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBanners(Banner banner)
        {
            base.AddObject("Banners", banner);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Partners EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPartners(Partner partner)
        {
            base.AddObject("Partners", partner);
        }

        #endregion

    }

    #endregion

    #region Entities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "ffiModel", Name = "Banner")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Banner : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Banner object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="partnerId">Initial value of the PartnerId property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        public static Banner CreateBanner(global::System.Guid id, global::System.Guid partnerId, global::System.String url, global::System.Byte[] image)
        {
            Banner banner = new Banner();
            banner.Id = id;
            banner.PartnerId = partnerId;
            banner.Url = url;
            banner.Image = image;
            return banner;
        }

        #endregion

        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid PartnerId
        {
            get
            {
                return _PartnerId;
            }
            set
            {
                OnPartnerIdChanging(value);
                ReportPropertyChanging("PartnerId");
                _PartnerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartnerId");
                OnPartnerIdChanged();
            }
        }
        private global::System.Guid _PartnerId;
        partial void OnPartnerIdChanging(global::System.Guid value);
        partial void OnPartnerIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();

        #endregion


        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ffiModel", "FK_Banners_Partners", "Partner")]
        public Partner Partner
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("ffiModel.FK_Banners_Partners", "Partner").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("ffiModel.FK_Banners_Partners", "Partner").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Partner> PartnerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("ffiModel.FK_Banners_Partners", "Partner");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Partner>("ffiModel.FK_Banners_Partners", "Partner", value);
                }
            }
        }

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "ffiModel", Name = "Category")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Category : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name_ru">Initial value of the Name_ru property.</param>
        /// <param name="name_en">Initial value of the Name_en property.</param>
        /// <param name="name_ua">Initial value of the Name_ua property.</param>
        /// <param name="index">Initial value of the Index property.</param>
        public static Category CreateCategory(global::System.Guid id, global::System.String name_ru, global::System.String name_en, global::System.String name_ua, global::System.Int32 index)
        {
            Category category = new Category();
            category.Id = id;
            category.Name_ru = name_ru;
            category.Name_en = name_en;
            category.Name_ua = name_ua;
            category.Index = index;
            return category;
        }

        #endregion

        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Name_ru
        {
            get
            {
                return _Name_ru;
            }
            set
            {
                OnName_ruChanging(value);
                ReportPropertyChanging("Name_ru");
                _Name_ru = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name_ru");
                OnName_ruChanged();
            }
        }
        private global::System.String _Name_ru;
        partial void OnName_ruChanging(global::System.String value);
        partial void OnName_ruChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Name_en
        {
            get
            {
                return _Name_en;
            }
            set
            {
                OnName_enChanging(value);
                ReportPropertyChanging("Name_en");
                _Name_en = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name_en");
                OnName_enChanged();
            }
        }
        private global::System.String _Name_en;
        partial void OnName_enChanging(global::System.String value);
        partial void OnName_enChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Name_ua
        {
            get
            {
                return _Name_ua;
            }
            set
            {
                OnName_uaChanging(value);
                ReportPropertyChanging("Name_ua");
                _Name_ua = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name_ua");
                OnName_uaChanged();
            }
        }
        private global::System.String _Name_ua;
        partial void OnName_uaChanging(global::System.String value);
        partial void OnName_uaChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 Index
        {
            get
            {
                return _Index;
            }
            set
            {
                OnIndexChanging(value);
                ReportPropertyChanging("Index");
                _Index = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Index");
                OnIndexChanged();
            }
        }
        private global::System.Int32 _Index;
        partial void OnIndexChanging(global::System.Int32 value);
        partial void OnIndexChanged();

        #endregion


        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ffiModel", "FK_Products_Categories", "Product")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("ffiModel.FK_Products_Categories", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("ffiModel.FK_Products_Categories", "Product", value);
                }
            }
        }

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "ffiModel", Name = "FAQ")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class FAQ : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new FAQ object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="question_ru">Initial value of the Question_ru property.</param>
        /// <param name="answer_ru">Initial value of the Answer_ru property.</param>
        /// <param name="showOnPartnerPanel">Initial value of the ShowOnPartnerPanel property.</param>
        public static FAQ CreateFAQ(global::System.Guid id, global::System.String question_ru, global::System.String answer_ru, global::System.Boolean showOnPartnerPanel)
        {
            FAQ fAQ = new FAQ();
            fAQ.Id = id;
            fAQ.Question_ru = question_ru;
            fAQ.Answer_ru = answer_ru;
            fAQ.ShowOnPartnerPanel = showOnPartnerPanel;
            return fAQ;
        }

        #endregion

        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Question_ru
        {
            get
            {
                return _Question_ru;
            }
            set
            {
                OnQuestion_ruChanging(value);
                ReportPropertyChanging("Question_ru");
                _Question_ru = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Question_ru");
                OnQuestion_ruChanged();
            }
        }
        private global::System.String _Question_ru;
        partial void OnQuestion_ruChanging(global::System.String value);
        partial void OnQuestion_ruChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        [AllowHtml]public global::System.String Answer_ru
        {
            get
            {
                return _Answer_ru;
            }
            set
            {
                OnAnswer_ruChanging(value);
                ReportPropertyChanging("Answer_ru");
                _Answer_ru = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Answer_ru");
                OnAnswer_ruChanged();
            }
        }
        private global::System.String _Answer_ru;
        partial void OnAnswer_ruChanging(global::System.String value);
        partial void OnAnswer_ruChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String Question_ua
        {
            get
            {
                return _Question_ua;
            }
            set
            {
                OnQuestion_uaChanging(value);
                ReportPropertyChanging("Question_ua");
                _Question_ua = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question_ua");
                OnQuestion_uaChanged();
            }
        }
        private global::System.String _Question_ua;
        partial void OnQuestion_uaChanging(global::System.String value);
        partial void OnQuestion_uaChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]public global::System.String Answer_ua
        {
            get
            {
                return _Answer_ua;
            }
            set
            {
                OnAnswer_uaChanging(value);
                ReportPropertyChanging("Answer_ua");
                _Answer_ua = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Answer_ua");
                OnAnswer_uaChanged();
            }
        }
        private global::System.String _Answer_ua;
        partial void OnAnswer_uaChanging(global::System.String value);
        partial void OnAnswer_uaChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String Question_en
        {
            get
            {
                return _Question_en;
            }
            set
            {
                OnQuestion_enChanging(value);
                ReportPropertyChanging("Question_en");
                _Question_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question_en");
                OnQuestion_enChanged();
            }
        }
        private global::System.String _Question_en;
        partial void OnQuestion_enChanging(global::System.String value);
        partial void OnQuestion_enChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]public global::System.String Answer_en
        {
            get
            {
                return _Answer_en;
            }
            set
            {
                OnAnswer_enChanging(value);
                ReportPropertyChanging("Answer_en");
                _Answer_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Answer_en");
                OnAnswer_enChanged();
            }
        }
        private global::System.String _Answer_en;
        partial void OnAnswer_enChanging(global::System.String value);
        partial void OnAnswer_enChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShowOnPartnerPanel
        {
            get
            {
                return _ShowOnPartnerPanel;
            }
            set
            {
                OnShowOnPartnerPanelChanging(value);
                ReportPropertyChanging("ShowOnPartnerPanel");
                _ShowOnPartnerPanel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowOnPartnerPanel");
                OnShowOnPartnerPanelChanged();
            }
        }
        private global::System.Boolean _ShowOnPartnerPanel;
        partial void OnShowOnPartnerPanelChanging(global::System.Boolean value);
        partial void OnShowOnPartnerPanelChanged();

        #endregion


    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "ffiModel", Name = "Partner")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Partner : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Partner object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="expirationDate">Initial value of the ExpirationDate property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="skype">Initial value of the Skype property.</param>
        /// <param name="contactsEmail">Initial value of the ContactsEmail property.</param>
        /// <param name="deliveryService">Initial value of the DeliveryService property.</param>
        /// <param name="fFILogin">Initial value of the FFILogin property.</param>
        public static Partner CreatePartner(global::System.Guid id, global::System.Guid userId, global::System.DateTime expirationDate, global::System.String name, global::System.String country, global::System.String city, global::System.String address, global::System.String phone, global::System.String skype, global::System.String contactsEmail, global::System.String deliveryService, global::System.String fFILogin)
        {
            Partner partner = new Partner();
            partner.Id = id;
            partner.UserId = userId;
            partner.ExpirationDate = expirationDate;
            partner.Name = name;
            partner.Country = country;
            partner.City = city;
            partner.Address = address;
            partner.Phone = phone;
            partner.Skype = skype;
            partner.ContactsEmail = contactsEmail;
            partner.DeliveryService = deliveryService;
            partner.FFILogin = fFILogin;
            return partner;
        }

        #endregion

        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpirationDate
        {
            get
            {
                return _ExpirationDate;
            }
            set
            {
                OnExpirationDateChanging(value);
                ReportPropertyChanging("ExpirationDate");
                _ExpirationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpirationDate");
                OnExpirationDateChanged();
            }
        }
        private global::System.DateTime _ExpirationDate;
        partial void OnExpirationDateChanging(global::System.DateTime value);
        partial void OnExpirationDateChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Skype
        {
            get
            {
                return _Skype;
            }
            set
            {
                OnSkypeChanging(value);
                ReportPropertyChanging("Skype");
                _Skype = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Skype");
                OnSkypeChanged();
            }
        }
        private global::System.String _Skype;
        partial void OnSkypeChanging(global::System.String value);
        partial void OnSkypeChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String ContactsEmail
        {
            get
            {
                return _ContactsEmail;
            }
            set
            {
                OnContactsEmailChanging(value);
                ReportPropertyChanging("ContactsEmail");
                _ContactsEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContactsEmail");
                OnContactsEmailChanged();
            }
        }
        private global::System.String _ContactsEmail;
        partial void OnContactsEmailChanging(global::System.String value);
        partial void OnContactsEmailChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String TestDriveHTML
        {
            get
            {
                return _TestDriveHTML;
            }
            set
            {
                OnTestDriveHTMLChanging(value);
                ReportPropertyChanging("TestDriveHTML");
                _TestDriveHTML = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TestDriveHTML");
                OnTestDriveHTMLChanged();
            }
        }
        private global::System.String _TestDriveHTML;
        partial void OnTestDriveHTMLChanging(global::System.String value);
        partial void OnTestDriveHTMLChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String DeliveryService
        {
            get
            {
                return _DeliveryService;
            }
            set
            {
                OnDeliveryServiceChanging(value);
                ReportPropertyChanging("DeliveryService");
                _DeliveryService = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DeliveryService");
                OnDeliveryServiceChanged();
            }
        }
        private global::System.String _DeliveryService;
        partial void OnDeliveryServiceChanging(global::System.String value);
        partial void OnDeliveryServiceChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String BannerUrl
        {
            get
            {
                return _BannerUrl;
            }
            set
            {
                OnBannerUrlChanging(value);
                ReportPropertyChanging("BannerUrl");
                _BannerUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BannerUrl");
                OnBannerUrlChanged();
            }
        }
        private global::System.String _BannerUrl;
        partial void OnBannerUrlChanging(global::System.String value);
        partial void OnBannerUrlChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.Byte[] BannerImage
        {
            get
            {
                return StructuralObject.GetValidValue(_BannerImage);
            }
            set
            {
                OnBannerImageChanging(value);
                ReportPropertyChanging("BannerImage");
                _BannerImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BannerImage");
                OnBannerImageChanged();
            }
        }
        private global::System.Byte[] _BannerImage;
        partial void OnBannerImageChanging(global::System.Byte[] value);
        partial void OnBannerImageChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String FFILogin
        {
            get
            {
                return _FFILogin;
            }
            set
            {
                OnFFILoginChanging(value);
                ReportPropertyChanging("FFILogin");
                _FFILogin = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FFILogin");
                OnFFILoginChanged();
            }
        }
        private global::System.String _FFILogin;
        partial void OnFFILoginChanging(global::System.String value);
        partial void OnFFILoginChanged();

        #endregion


        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ffiModel", "FK_Banners_Partners", "Banner")]
        public EntityCollection<Banner> Banners
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Banner>("ffiModel.FK_Banners_Partners", "Banner");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Banner>("ffiModel.FK_Banners_Partners", "Banner", value);
                }
            }
        }

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ffiModel", "FK_Payments_Partners", "Payment")]
        public EntityCollection<Payment> Payments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Payment>("ffiModel.FK_Payments_Partners", "Payment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Payment>("ffiModel.FK_Payments_Partners", "Payment", value);
                }
            }
        }

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ffiModel", "FK_Results_Partners", "Result")]
        public EntityCollection<Result> Results
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Result>("ffiModel.FK_Results_Partners", "Result");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Result>("ffiModel.FK_Results_Partners", "Result", value);
                }
            }
        }

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "ffiModel", Name = "Payment")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Payment : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Payment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="partnerId">Initial value of the PartnerId property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="paymentFor">Initial value of the PaymentFor property.</param>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="completed">Initial value of the Completed property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        public static Payment CreatePayment(global::System.Guid id, global::System.Guid partnerId, global::System.Int32 amount, global::System.String paymentFor, global::System.Int32 orderId, global::System.Boolean completed, global::System.DateTime createdAt)
        {
            Payment payment = new Payment();
            payment.Id = id;
            payment.PartnerId = partnerId;
            payment.Amount = amount;
            payment.PaymentFor = paymentFor;
            payment.OrderId = orderId;
            payment.Completed = completed;
            payment.CreatedAt = createdAt;
            return payment;
        }

        #endregion

        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid PartnerId
        {
            get
            {
                return _PartnerId;
            }
            set
            {
                OnPartnerIdChanging(value);
                ReportPropertyChanging("PartnerId");
                _PartnerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartnerId");
                OnPartnerIdChanged();
            }
        }
        private global::System.Guid _PartnerId;
        partial void OnPartnerIdChanging(global::System.Guid value);
        partial void OnPartnerIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Int32 _Amount;
        partial void OnAmountChanging(global::System.Int32 value);
        partial void OnAmountChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String PaymentFor
        {
            get
            {
                return _PaymentFor;
            }
            set
            {
                OnPaymentForChanging(value);
                ReportPropertyChanging("PaymentFor");
                _PaymentFor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PaymentFor");
                OnPaymentForChanged();
            }
        }
        private global::System.String _PaymentFor;
        partial void OnPaymentForChanging(global::System.String value);
        partial void OnPaymentForChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private global::System.Int32 _OrderId;
        partial void OnOrderIdChanging(global::System.Int32 value);
        partial void OnOrderIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Boolean Completed
        {
            get
            {
                return _Completed;
            }
            set
            {
                OnCompletedChanging(value);
                ReportPropertyChanging("Completed");
                _Completed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Completed");
                OnCompletedChanged();
            }
        }
        private global::System.Boolean _Completed;
        partial void OnCompletedChanging(global::System.Boolean value);
        partial void OnCompletedChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();

        #endregion


        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ffiModel", "FK_Payments_Partners", "Partner")]
        public Partner Partner
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("ffiModel.FK_Payments_Partners", "Partner").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("ffiModel.FK_Payments_Partners", "Partner").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Partner> PartnerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("ffiModel.FK_Payments_Partners", "Partner");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Partner>("ffiModel.FK_Payments_Partners", "Partner", value);
                }
            }
        }

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "ffiModel", Name = "Product")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Product : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name_en">Initial value of the Name_en property.</param>
        /// <param name="name_ua">Initial value of the Name_ua property.</param>
        /// <param name="name_ru">Initial value of the Name_ru property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static Product CreateProduct(global::System.Guid id, global::System.String name_en, global::System.String name_ua, global::System.String name_ru, global::System.Int32 price)
        {
            Product product = new Product();
            product.Id = id;
            product.Name_en = name_en;
            product.Name_ua = name_ua;
            product.Name_ru = name_ru;
            product.Price = price;
            return product;
        }

        #endregion

        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Name_en
        {
            get
            {
                return _Name_en;
            }
            set
            {
                OnName_enChanging(value);
                ReportPropertyChanging("Name_en");
                _Name_en = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name_en");
                OnName_enChanged();
            }
        }
        private global::System.String _Name_en;
        partial void OnName_enChanging(global::System.String value);
        partial void OnName_enChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Name_ua
        {
            get
            {
                return _Name_ua;
            }
            set
            {
                OnName_uaChanging(value);
                ReportPropertyChanging("Name_ua");
                _Name_ua = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name_ua");
                OnName_uaChanged();
            }
        }
        private global::System.String _Name_ua;
        partial void OnName_uaChanging(global::System.String value);
        partial void OnName_uaChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Name_ru
        {
            get
            {
                return _Name_ru;
            }
            set
            {
                OnName_ruChanging(value);
                ReportPropertyChanging("Name_ru");
                _Name_ru = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name_ru");
                OnName_ruChanged();
            }
        }
        private global::System.String _Name_ru;
        partial void OnName_ruChanging(global::System.String value);
        partial void OnName_ruChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]
        public global::System.String Description_ua
        {
            get
            {
                return _Description_ua;
            }
            set
            {
                OnDescription_uaChanging(value);
                ReportPropertyChanging("Description_ua");
                _Description_ua = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description_ua");
                OnDescription_uaChanged();
            }
        }
        private global::System.String _Description_ua;
        partial void OnDescription_uaChanging(global::System.String value);
        partial void OnDescription_uaChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]
        public global::System.String Description_ru
        {
            get
            {
                return _Description_ru;
            }
            set
            {
                OnDescription_ruChanging(value);
                ReportPropertyChanging("Description_ru");
                _Description_ru = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description_ru");
                OnDescription_ruChanged();
            }
        }
        private global::System.String _Description_ru;
        partial void OnDescription_ruChanging(global::System.String value);
        partial void OnDescription_ruChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]
        public global::System.String Description_en
        {
            get
            {
                return _Description_en;
            }
            set
            {
                OnDescription_enChanging(value);
                ReportPropertyChanging("Description_en");
                _Description_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description_en");
                OnDescription_enChanged();
            }
        }
        private global::System.String _Description_en;
        partial void OnDescription_enChanging(global::System.String value);
        partial void OnDescription_enChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private Nullable<global::System.Guid> _CategoryId;
        partial void OnCategoryIdChanging(Nullable<global::System.Guid> value);
        partial void OnCategoryIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Int32 Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Int32 _Price;
        partial void OnPriceChanging(global::System.Int32 value);
        partial void OnPriceChanged();

        #endregion


        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ffiModel", "FK_Products_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("ffiModel.FK_Products_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("ffiModel.FK_Products_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("ffiModel.FK_Products_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("ffiModel.FK_Products_Categories", "Category", value);
                }
            }
        }

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "ffiModel", Name = "Result")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Result : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="manufacturer">Initial value of the Manufacturer property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="videoTag">Initial value of the VideoTag property.</param>
        /// <param name="isActive">Initial value of the isActive property.</param>
        public static Result CreateResult(global::System.Guid id, global::System.String manufacturer, global::System.String model, global::System.String videoTag, global::System.Boolean isActive)
        {
            Result result = new Result();
            result.Id = id;
            result.Manufacturer = manufacturer;
            result.Model = model;
            result.VideoTag = videoTag;
            result.isActive = isActive;
            return result;
        }

        #endregion

        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                OnManufacturerChanging(value);
                ReportPropertyChanging("Manufacturer");
                _Manufacturer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Manufacturer");
                OnManufacturerChanged();
            }
        }
        private global::System.String _Manufacturer;
        partial void OnManufacturerChanging(global::System.String value);
        partial void OnManufacturerChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.String VideoTag
        {
            get
            {
                return _VideoTag;
            }
            set
            {
                OnVideoTagChanging(value);
                ReportPropertyChanging("VideoTag");
                _VideoTag = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VideoTag");
                OnVideoTagChanged();
            }
        }
        private global::System.String _VideoTag;
        partial void OnVideoTagChanging(global::System.String value);
        partial void OnVideoTagChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]
        public global::System.String Description_ua
        {
            get
            {
                return _Description_ua;
            }
            set
            {
                OnDescription_uaChanging(value);
                ReportPropertyChanging("Description_ua");
                _Description_ua = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description_ua");
                OnDescription_uaChanged();
            }
        }
        private global::System.String _Description_ua;
        partial void OnDescription_uaChanging(global::System.String value);
        partial void OnDescription_uaChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]
        public global::System.String Description_ru
        {
            get
            {
                return _Description_ru;
            }
            set
            {
                OnDescription_ruChanging(value);
                ReportPropertyChanging("Description_ru");
                _Description_ru = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description_ru");
                OnDescription_ruChanged();
            }
        }
        private global::System.String _Description_ru;
        partial void OnDescription_ruChanging(global::System.String value);
        partial void OnDescription_ruChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]
        public global::System.String Description_en
        {
            get
            {
                return _Description_en;
            }
            set
            {
                OnDescription_enChanging(value);
                ReportPropertyChanging("Description_en");
                _Description_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description_en");
                OnDescription_enChanged();
            }
        }
        private global::System.String _Description_en;
        partial void OnDescription_enChanging(global::System.String value);
        partial void OnDescription_enChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Boolean isActive
        {
            get
            {
                return _isActive;
            }
            set
            {
                OnisActiveChanging(value);
                ReportPropertyChanging("isActive");
                _isActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isActive");
                OnisActiveChanged();
            }
        }
        private global::System.Boolean _isActive;
        partial void OnisActiveChanging(global::System.Boolean value);
        partial void OnisActiveChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> PartnerId
        {
            get
            {
                return _PartnerId;
            }
            set
            {
                OnPartnerIdChanging(value);
                ReportPropertyChanging("PartnerId");
                _PartnerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartnerId");
                OnPartnerIdChanged();
            }
        }
        private Nullable<global::System.Guid> _PartnerId;
        partial void OnPartnerIdChanging(Nullable<global::System.Guid> value);
        partial void OnPartnerIdChanged();

        #endregion


        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ffiModel", "FK_Results_Partners", "Partner")]
        public Partner Partner
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("ffiModel.FK_Results_Partners", "Partner").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("ffiModel.FK_Results_Partners", "Partner").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Partner> PartnerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("ffiModel.FK_Results_Partners", "Partner");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Partner>("ffiModel.FK_Results_Partners", "Partner", value);
                }
            }
        }

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName = "ffiModel", Name = "Slide")]
    [Serializable()]
    [DataContractAttribute(IsReference = true)]
    public partial class Slide : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Slide object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        public static Slide CreateSlide(global::System.Guid id, global::System.Byte[] image)
        {
            Slide slide = new Slide();
            slide.Id = id;
            slide.Image = image;
            return slide;
        }

        #endregion

        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]
        public global::System.String Description_ua
        {
            get
            {
                return _Description_ua;
            }
            set
            {
                OnDescription_uaChanging(value);
                ReportPropertyChanging("Description_ua");
                _Description_ua = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description_ua");
                OnDescription_uaChanged();
            }
        }
        private global::System.String _Description_ua;
        partial void OnDescription_uaChanging(global::System.String value);
        partial void OnDescription_uaChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]
        public global::System.String Description_ru
        {
            get
            {
                return _Description_ru;
            }
            set
            {
                OnDescription_ruChanging(value);
                ReportPropertyChanging("Description_ru");
                _Description_ru = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description_ru");
                OnDescription_ruChanged();
            }
        }
        private global::System.String _Description_ru;
        partial void OnDescription_ruChanging(global::System.String value);
        partial void OnDescription_ruChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
        [DataMemberAttribute()]
        [AllowHtml]
        public global::System.String Description_en
        {
            get
            {
                return _Description_en;
            }
            set
            {
                OnDescription_enChanging(value);
                ReportPropertyChanging("Description_en");
                _Description_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description_en");
                OnDescription_enChanged();
            }
        }
        private global::System.String _Description_en;
        partial void OnDescription_enChanging(global::System.String value);
        partial void OnDescription_enChanged();

        #endregion


    }

    #endregion


}
